[theme]
primaryColor="#034694"
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#e0e2e6"
textColor="#262730"
font="sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false